---
version: 3.9
services:
  student-srv:
    build:
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - student-net-qa
    environment:
      - MYSQL_SERVER=students-db-qa
    depends_on:
      - student-db
  student-db-qa:
    image: mysql:5.6
    networks:
      - student-privatenet-qa
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
    volumes:
      - type: volume
        source: student-db-qa
        target: /var/lib/mysql
volumes:
  student-db-qa:    
networks:
  student-net-qa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
  student-privatenet-qa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
    
    